### ISSUE TITLE
tag release

### ISSUE THREAD

**Issue by Ken-B** [simonster/Memoize.jl#2]
Hi Simon,

Thanks for this package. I added Memoize to the REQUIRE file of a package of mine, but in a fresh Julia 0.4 installation it downloaded commit 809277db70fb62b46d54246ce2d7b20428e4cf07, not the latest master. Very strange.

Could you perhaps tag the latest master?

Thank you,
Ken

**Comment by slundberg** [comment]
Also have the same issue. Tagging would be good.

**Comment by simonster** [comment]
Closed by JuliaLang/METADATA.jl#3895
